{
 "title": "PBS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "LXC/VM",
    "query": {
     "query": "label_values(pbs_snapshot_count,comment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_gc_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Datastore Total Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_datastore_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Datastore Used Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_datastore_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Number of Snapshots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pbs_snapshot_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LXC and VM Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(pbs_snapshot_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Prune Job Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_last_run_timestamp{worker_type=\"prunejob\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Verification Job Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_last_run_timestamp{worker_type=\"verificationjob\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup Job Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_last_run_timestamp{worker_type=\"backup\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update Job Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_last_run_timestamp{worker_type=\"aptupdate\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last GC Job Run",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_last_run_timestamp{worker_type=\"garbage_collection\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC removed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_gc_removed_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Pending Removal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_gc_pending_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_memory_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pbs_host_memory_used_bytes / pbs_host_memory_total_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Delay",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_io_wait * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1-Minute CPU Load Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5-Minute CPU Load Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "15-Minute CPU Load Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pbs_host_load15", "legendFormat": "__auto" }
   ]
  },
  { "title": "Snapshots Info ($system)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Snapshot Count",
   "type": "stat",
   "description": "Total number of snapshot counts for selected LXC/VM",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_snapshot_count{comment=\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verified Snapshot",
   "type": "stat",
   "description": "Total number of verified snapshots for the selected LXC/VM",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_verified{comment=\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Un-verified Snapshot",
   "type": "stat",
   "description": "Total number of un-verified snapshots for the selected LXC/VM",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pbs_snapshot_verified{comment=\"$system\"}) - sum(pbs_snapshot_verified{comment=\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Size",
   "type": "stat",
   "description": "Total number of snapshots size for the selected LXC/VM",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_size_bytes{comment=\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Snapshot Job Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_duration_seconds{comment=\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Snapshot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pbs_snapshot_last_timestamp_seconds{comment=\"$system\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Snapshot Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (backup_id, comment) (pbs_snapshot_size_bytes{comment=\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent No of Backup Task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_task_total{comment=\"$system\", worker_type=\"backup\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots timeline",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_snapshot_size_bytes{comment=\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 36 },
   "targets": [
    { "expr": "pbs_host_cpu_usage * 100", "legendFormat": "CPU %" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "pbs_host_memory_used_bytes", "legendFormat": "Total Used" },
    { "expr": "pbs_host_memory_total_bytes", "legendFormat": "Total Available" },
    { "expr": "pbs_host_memory_free_bytes", "legendFormat": "Total Free" }
   ]
  },
  {
   "title": "I/O Delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 47 },
   "targets": [
    { "expr": "pbs_host_io_wait * 100", "legendFormat": "IO Delay" }
   ]
  },
  {
   "title": "CPU Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 47 },
   "targets": [
    { "expr": "pbs_host_load1", "legendFormat": "1 minute load" },
    { "expr": "pbs_host_load5", "legendFormat": "5 minute load" },
    { "expr": "pbs_host_load15", "legendFormat": "15 minute load" }
   ]
  }
 ]
}